baseurl: /mobius-eng.github.io
title: "MobiusEng: Math Science Engineering"
subtitle: math and programming
author: Alexey Cherkaev (aka mobius-eng)
simple_search: http://google.com/search
description: Site for math and programming geeks and nerds
name: MobiusEng
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /articles/:short_year/:title
timezone: America/New_York
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: atom
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/Programs/
